### PR TITLE
Automatic test generation rewritten

### PR DESCRIPTION
**Pull request by GH-James**
Added new automatic_testgen.py alongside accompanying help and config files.

Added functionality to automatic test generation
- genpmls
- spin
- gentests
- clean
- copy
- archive

Restructured automatic_testgen.py to be more similar to testbuilder.py

### CODE REVIEW

**Comment by andrewbutterfield** [comment]
How do I run automatic generation ? How do I install it properly


I setup an alias `au` 

```
alias au='$HOME/REPOS/RTEMS-SMP-Formal/formal/promela/src/automatic_testgen.py'
```
but when I run it I get a strange message and the terminal window and the whole Ubuntu desktop locks up. If have to do a lot of control-C, control-D and control-Z to get back control

I also had to give `automatic_testgen.py` execute privileges to run at all.

Can you update README to explain how to setup the automatic stuff

**Comment by andrewbutterfield** [comment]
When I run `au help` I get the terminal cursor turning into a cross, and the message
```
from: can't read /var/mail/src.modules.promela_yacc.promela
```

Any mouse click just causes the followng response:
```
import-in6.q16: attempt to perform operation not allowed by security policy `PS'@ error/constitute.c/IsCoderAuthorized/408
```
It takes several control-Ds to break out of this. Google the above message for more details

**Comment by GH-James** [comment]
It appears that the issue arises because I did not include a shebang at the beginning of the file
I had been testing by calling python directly rather than with an alias.

I'll fix that and update the readme shortly.

As for using the system, the setup should be the same as testbuilder in all other areas.
The Promela parser library will sometimes reject valid Promela code for syntax errors, I'm not entirely sure why.

I tested using the following steps:
- .../formal/proto/freechain-src/spfreechain.pml
- make a directory .../formal/promela/models/spfreechain
- copied the into .../formal/promela/models/spfreechain
- added an entry to models.yml "spfreechain: spfreechain/spfreechain"
- copied all refinement files from .../formal/promela/models/chains/ to .../formal/promal/models/spfreechain/ with "chains" replaced with "spfreechain" in model names

At that point all steps should work other than compile/run.
All steps from clean->genpmls->spin->gentests produce the expected output with the given inputs.
The code generated is not valid as the model is not designed to be used with those refinement files, so compilation will fail.

**Comment by GH-James** [comment]
Upon further investigation, the alias should be set up to be:
`alias au='python3 $HOME/REPOS/RTEMS-SMP-Formal/formal/promela/src/automatic_testgen.py'`

**Comment by andrewbutterfield** [comment]
I don't see `spfreechain.pml` in `../formal/proto/freechain-src/spfreechain.pml`, I see `testsuites_spfreechain01.pml` which inlcudes `cpukit.pml`. Is this what you meant?

**Comment by andrewbutterfield** [comment]
I initially see an error about max_trails not being specificed - can you add that to the template?

**Comment by GH-James** [comment]
> I don't see `spfreechain.pml` in `../formal/proto/freechain-src/spfreechain.pml`, I see `testsuites_spfreechain01.pml` which inlcudes `cpukit.pml`. Is this what you meant?

That is what I was referring to, you will need to copy both of those files, and rename `testsuites_spfreechain01.pml` to `spfreechain.pml`

**Comment by GH-James** [comment]
> I initially see an error about max_trails not being specificed - can you add that to the template?

I have now removed this from the required keys, it shouldn't throw an error.
I hadn't realised I defined it in a local config copy while testing.

**Comment by andrewbutterfield** [comment]
When I do `genpmls` I get the following error after some other stuff has been done:

```
Generating spin files for assert_get_0

.... skipping a load of C compiler warnings

pan:1: assertion violated  !((chain.head==0)) (at depth 12)
pan: wrote assert_get_0.pml1.trail

(Spin Version 6.4.9 -- 17 December 2018)
	+ Partial Order Reduction

.... skips SPIN reporting

pan: elapsed time 0 seconds
error executing: spin -T -t assert_get_0.pml > assert_get_0.spn
```
When we look into `assert_get_0.spn` we see
```
(env) freechain$ more assert_get_0.spn
spin: cannot find trail file
```
If we add a number to `-t` we get

```
(env) freechain$ spin -T -t1 assert_get_0.pml > assert_get_0_1.spn
(env) freechain$ more assert_get_0_1.spn 

 Chain Model running.
@@@ 0 NAME Chain_AutoGen
@@@ 0 DEF MAX_SIZE 8
@@@ 0 DCLARRAY Node memory MAX_SIZE
@@@ 0 DECL unsigned nptr NULL
@@@ 0 DECL Control chain

Initialising...
@@@ 0 INIT
@@@ 0 SEQ chain
@@@ 0 END chain
@@@ 0 PTR nptr 0
spin: assert_get_0.pml:121, Error: assertion violated
spin: text of failed assertion: assert(!((chain.head==0)))
spin: trail ends after 13 steps
#processes: 2
		memory[0].nxt = 0
		memory[0].prv = 0
		memory[0].itm = 0
		memory[1].nxt = 0
		memory[1].prv = 0
		memory[1].itm = 0
		memory[2].nxt = 0
		memory[2].prv = 0
		memory[2].itm = 0
		memory[3].nxt = 0
		memory[3].prv = 0
		memory[3].itm = 0
		memory[4].nxt = 0
		memory[4].prv = 0
		memory[4].itm = 0
		memory[5].nxt = 0
		memory[5].prv = 0
		memory[5].itm = 0
		memory[6].nxt = 0
		memory[6].prv = 0
		memory[6].itm = 0
		memory[7].nxt = 0
		memory[7].prv = 0
		memory[7].itm = 0
		memory0[0] = 0
		memory0[1] = 0
		memory0[2] = 0
		memory0[3] = 0
		memory0[4] = 0
		memory0[5] = 0
		memory0[6] = 0
		memory0[7] = 0
		nptr = 0
		chain.head = 0
		chain.tail = 0
		chain.size = 0
 13:	proc  1 (doGet:1) assert_get_0.pml:140 (state 22)
 13:	proc  0 (:init::1) assert_get_0.pml:192 (state 53)
2 processes created
```

Any time you have a trail file with extension of the form `.pmlN.trail` you need to use `-tN` with SPIN, rather than just `-t`.

**Comment by GH-James** [comment]
I assume the issue is with the `spin` command
It uses the existing logic from `testbuilder.py` to generate trail and spn files.

```
    if no_of_trails == 0:
        print("no trail files generated")
    elif no_of_trails == 1:
        subprocess.run(f"spin -T -t {model}.pml > {model}.spn",
                       check=True, shell=True)
    else:
        for i in range(no_of_trails):
            subprocess.run(f"spin -T -t{i + 1} {model}.pml > {model}-{i}.spn",
                           check=True, shell=True)
```

This is an artefact from the initial upload
```
if no_of_trails == 1:
        os.system("spin -T -t " + model + ".pml > " + model + ".spn")
        os.system(testgen + " " + model)
        sys.exit(0)
```

I'm not sure if there is a reason to have the case without a number after `-t`? 
If not, I think the `elif` can be removed, as that specifically does not add a number after `-t`

`genpmls` should only be generating alternative Promela files for each assertion/ltl

**Comment by andrewbutterfield** [comment]
Yes - it dates from a time when we would have one test done - it made sense then.

I'll remove the `elif`  - you should focus on other things at this stage, in any.

I'm puzzled why `genpmls` worked for you but not for me.

Anyway I'll make the change and re-run.

**Comment by andrewbutterfield** [comment]
I commented out the `elif`, but then decided to do a manual run to ensure nothing had broken.

I get the following outcome 
```
(env) src$ tb clean allmodels
Removing spin and test files for barrier-mgr-model
Removing spin and test files for chains-api-model
Removing spin and test files for event-mgr-model
Removing spin and test files for msg-mgr-model
Removing spin and test files for freechain-model
(env) src$ tb allsteps event-mgr-model
Traceback (most recent call last):
  File "/home/butrfeld/REPOS/RTEMS-SMP-Formal/formal/promela/src/testbuilder.py", line 466, in <module>
    main()
  File "/home/butrfeld/REPOS/RTEMS-SMP-Formal/formal/promela/src/testbuilder.py", line 432, in main
    all_steps(sys.argv[2::], model_to_path, source_dir)
  File "/home/butrfeld/REPOS/RTEMS-SMP-Formal/formal/promela/src/testbuilder.py", line 62, in all_steps
    clean(model, path, source_dir)
  File "/home/butrfeld/REPOS/RTEMS-SMP-Formal/formal/promela/src/testbuilder.py", line 83, in clean
    model_dir = model_to_path[model_name]
TypeError: 'PosixPath' object is not subscriptable
```

Any thoughts here?

**Comment by andrewbutterfield** [comment]
`au spin` works well - takes a while and creates 9242 .spn files!

**Comment by andrewbutterfield** [comment]
I had a look - added print statements to show types

In line 2, `path` should have been `model_to_path`. Now it all works.

**Review by andrewbutterfield — APPROVED** [review]
Happy now

**Pull request merged**
