### PR TITLE
Updated pattern matching to vanilla python 3.10

### PR DESCRIPTION
**Pull request by GH-James**
Removed all coconut syntax from refine_command.coco, src/src/spin2test.coco
Copied above directly into refine_command.py, src/src/spin2test.py
Updated .gitignore to track python files

### CODE REVIEW

**Comment by GH-James** [comment]
closes #15

**Comment by andrewbutterfield** [comment]
I get the followng error trying to setup the requirements, using python3.10

Any ideas?

```
Installing collected packages: yapf, wrapt, wcwidth, typing-extensions, typed-ast, ply, parsec, mypy-extensions, mccabe, iniconfig, cPyparsing, zipp, toml, six, PyYAML, pyparsing, Pygments, pyflakes, pycodestyle, py, prompt-toolkit, pluggy, mypy, lazy-object-proxy, isort, decorator, coverage, attrs, packaging, networkx, importlib-metadata, flake8, coconut, astroid, pytest, pylint
  DEPRECATION: wrapt is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for wrapt ... done
  DEPRECATION: typed-ast is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for typed-ast ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for typed-ast did not run successfully.
  │ exit code: 1
  ╰─> [85 lines of output]
      running install
      /Users/butrfeld/REPOS/RTEMS-SMP-Formal/formal/promela/src/env/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-310
      creating build/lib.macosx-10.9-universal2-cpython-310/typed_ast
      copying typed_ast/conversions.py -> build/lib.macosx-10.9-universal2-cpython-310/typed_ast
      copying typed_ast/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/typed_ast
      copying typed_ast/ast3.py -> build/lib.macosx-10.9-universal2-cpython-310/typed_ast
      copying typed_ast/ast27.py -> build/lib.macosx-10.9-universal2-cpython-310/typed_ast
      creating build/lib.macosx-10.9-universal2-cpython-310/typed_ast/tests
      copying ast3/tests/test_basics.py -> build/lib.macosx-10.9-universal2-cpython-310/typed_ast/tests
      running build_ext
      building '_ast27' extension
      creating build/temp.macosx-10.9-universal2-cpython-310
      creating build/temp.macosx-10.9-universal2-cpython-310/ast27
      creating build/temp.macosx-10.9-universal2-cpython-310/ast27/Custom
      creating build/temp.macosx-10.9-universal2-cpython-310/ast27/Parser
      creating build/temp.macosx-10.9-universal2-cpython-310/ast27/Python
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Iast27/Include -I/Users/butrfeld/REPOS/RTEMS-SMP-Formal/formal/promela/src/env/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c ast27/Custom/typed_ast.c -o build/temp.macosx-10.9-universal2-cpython-310/ast27/Custom/typed_ast.o
      In file included from ast27/Custom/typed_ast.c:2:
      In file included from ast27/Include/Python-ast.h:3:
      ast27/Include/asdl.h:37:41: error: unknown type name 'PyArena'
      asdl_seq *asdl_seq_new(Py_ssize_t size, PyArena *arena);
                                              ^
      ast27/Include/asdl.h:38:49: error: unknown type name 'PyArena'
      asdl_int_seq *asdl_int_seq_new(Py_ssize_t size, PyArena *arena);
                                                      ^
      In file included from ast27/Custom/typed_ast.c:2:
      ast27/Include/Python-ast.h:398:63: error: unknown type name 'PyArena'
      mod_ty _Ta27_Module(asdl_seq * body, asdl_seq * type_ignores, PyArena *arena);
                                                                    ^
      ast27/Include/Python-ast.h:400:43: error: unknown type name 'PyArena'
      mod_ty _Ta27_Interactive(asdl_seq * body, PyArena *arena);
                                                ^
      ast27/Include/Python-ast.h:402:39: error: unknown type name 'PyArena'
      mod_ty _Ta27_Expression(expr_ty body, PyArena *arena);
                                            ^
      ast27/Include/Python-ast.h:404:65: error: unknown type name 'PyArena'
      mod_ty _Ta27_FunctionType(asdl_seq * argtypes, expr_ty returns, PyArena *arena);
                                                                      ^
      ast27/Include/Python-ast.h:406:37: error: unknown type name 'PyArena'
      mod_ty _Ta27_Suite(asdl_seq * body, PyArena *arena);
                                          ^
      ast27/Include/Python-ast.h:409:92: error: unknown type name 'PyArena'
                                decorator_list, string type_comment, int lineno, int col_offset, PyArena
                                                                                                 ^
      ast27/Include/Python-ast.h:413:68: error: unknown type name 'PyArena'
                             decorator_list, int lineno, int col_offset, PyArena *arena);
                                                                         ^
      ast27/Include/Python-ast.h:415:65: error: unknown type name 'PyArena'
      stmt_ty _Ta27_Return(expr_ty value, int lineno, int col_offset, PyArena *arena);
                                                                      ^
      ast27/Include/Python-ast.h:417:70: error: unknown type name 'PyArena'
      stmt_ty _Ta27_Delete(asdl_seq * targets, int lineno, int col_offset, PyArena *arena);
                                                                           ^
      ast27/Include/Python-ast.h:420:34: error: unknown type name 'PyArena'
                           col_offset, PyArena *arena);
                                       ^
      ast27/Include/Python-ast.h:423:25: error: unknown type name 'PyArena'
                              PyArena *arena);
                              ^
      ast27/Include/Python-ast.h:425:91: error: unknown type name 'PyArena'
      stmt_ty _Ta27_Print(expr_ty dest, asdl_seq * values, bool nl, int lineno, int col_offset, PyArena
                                                                                                ^
      ast27/Include/Python-ast.h:429:61: error: unknown type name 'PyArena'
                        type_comment, int lineno, int col_offset, PyArena *arena);
                                                                  ^
      ast27/Include/Python-ast.h:432:21: error: unknown type name 'PyArena'
                          PyArena *arena);
                          ^
      ast27/Include/Python-ast.h:435:18: error: unknown type name 'PyArena'
                       PyArena *arena);
                       ^
      ast27/Include/Python-ast.h:438:62: error: unknown type name 'PyArena'
                         type_comment, int lineno, int col_offset, PyArena *arena);
                                                                   ^
      ast27/Include/Python-ast.h:440:92: error: unknown type name 'PyArena'
      stmt_ty _Ta27_Raise(expr_ty type, expr_ty inst, expr_ty tback, int lineno, int col_offset, PyArena
                                                                                                 ^
      fatal error: too many errors emitted, stopping now [-ferror-limit=]
      20 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> typed-ast

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
make: *** [env] Error 1
src% 
```

**Comment by andrewbutterfield** [comment]
I decide to press on, so activate the environment  and try to `make py`:
```
src% . env/bin/activate
(env) src% make py
test -n "$VIRTUAL_ENV"
coconut --target 3 spin2test.coco spin2test.py
make: coconut: No such file or directory
make: *** [spin2test.py] Error 1
```
If I look at Makefile I see

```
(env) src% more Makefile
# SPDX-License-Identifier: BSD-2-Clause
# https://gitrepos.estec.esa.int/external/rtems-smp-qualification-qual/-/blob/ef082e24b0047790c38a9bef14414849a2ba6d5b/Makefile

DIR_SRC = src
DIR_TESTS = $(DIR_SRC)/tests
COCO_SRC_FILES = $(wildcard *.coco $(DIR_SRC)/*.coco $(DIR_TESTS)/*.coco)
PY_GEN_FILES = $(patsubst %.coco,%.py,$(COCO_SRC_FILES))

.PHONY: all py check format analyse metric git-hash-object-calculate sha512sum-calculate check-env coverage-report env clean

all: check format analyse coverage-report

%.py: %.coco | check-env
        coconut --target 3 $< $@

py: $(PY_GEN_FILES) | check-env

check: $(PY_GEN_FILES) | check-env
        coverage run --branch -m pytest --capture=tee-sys -vv -s $(DIR_TESTS)/test_coverage_testgen.py $(DIR_TESTS)/test_coverage_spin2test.py

format: $(PY_GEN_FILES) | check-env
        yapf -i --parallel $^

analyse: $(PY_GEN_FILES) | check-env
        flake8 $^
        mypy $^
        pylint --disable=duplicate-code --disable=unspecified-encoding --disable=consider-using-dict-items --disable=use-list-literal --disable=consider-using-with $^

metric: $(PY_GEN_FILES) | check-env
        python3 metrics.py $(PY_GEN_FILES)

git-hash-object-calculate:
        git hash-object $(COCO_SRC_FILES)

sha512sum-calculate:
        sha512sum $(COCO_SRC_FILES)

check-env:
        test -n "$$VIRTUAL_ENV"

EMPTY :=
SPACE := $(EMPTY) $(EMPTY)
COMMA := ,

coverage-report: | check-env
        coverage report -m --fail-under=100 --include=$(subst $(SPACE),$(COMMA),$(PY_GEN_FILES))

# sudo apt-get install python3-venv python3-dev
env:
        python3 -m venv env
        . env/bin/activate && pip install --upgrade pip && pip install -r requirements.txt

clean:
        rm -rf $(PY_GEN_FILES) .coverage .mypy_cache .pytest_cache
        find $(DIR_SRC) -name __pycache__ -exec rm -rf '{}' +
(END)
```

I'm in your branch:
```
(env) src% git log
commit 7b1af329f243be998f52d52d702efaa59f034970 (HEAD -> SoftwareSupportJames, origin/SoftwareSupportJames)
Author: GH-James <78970503+GH-James@users.noreply.github.com>
Date:   Fri Feb 17 01:19:27 2023 +0000

    Removed refine_command.coco, src/src/spin2test.coco and replaced with python files
    Updated gitignore to track relevant python files

commit 68f226c086bd6fcc0e810564c4489c7c69116ba2
Author: GH-James <78970503+GH-James@users.noreply.github.com>
Date:   Thu Feb 16 15:26:13 2023 +0000

    Use python native map instead of coconut fmap in src/spin2test.coco

....
```

Did you commit changes to `Makefile`? I don't see any

**Comment by GH-James** [comment]
It looks like the coconut command is failing because coconut is not installed in your active environment.

I would guess that because typed-ast failed to install, that none of the packages in requirements.txt were installed.

Ill dig into this and fix the requirements.txt.

There were no changes to the Makefile, as COCO_SRC_FILES and subsequently PYTHON_GEN_FILES will only pick up files with coconut counterparts.
The coconut files have been deleted where relevant, and wont be picked up as a result.

**Comment by andrewbutterfield** [comment]
OK – thanks.

--------------------------------------------------------------------
Andrew Butterfield     Tel: +353-1-896-2517     Fax: +353-1-677-2204
***@***.***, Head of Software Foundations & Verification Research Group
School of Computer Science and Statistics,
Room G.39, O'Reilly Institute, Trinity College, University of Dublin
                         http://www.scss.tcd.ie/Andrew.Butterfield/
--------------------------------------------------------------------


From: James Gooding Hunt ***@***.***>
Reply to: andrewbutterfield/RTEMS-SMP-Formal ***@***.***>
Date: Friday 17 February 2023 at 11:16
To: andrewbutterfield/RTEMS-SMP-Formal ***@***.***>
Cc: ***@***.***" ***@***.***>, Comment ***@***.***>
Subject: Re: [andrewbutterfield/RTEMS-SMP-Formal] Updated pattern matching to vanilla python 3.10 (PR #19)


It looks like the coconut command is failing because coconut is not installed in your active environment.

I would guess that because typed-ast failed to install, that none of the packages in requirements.txt were installed.

Ill dig into this and fix the requirements.txt.

There were no changes to the Makefile, as COCO_SRC_FILES and subsequently PYTHON_GEN_FILES will only pick up files with coconut counterparts.
The coconut files have been deleted where relevant, and wont be picked up as a result.

**Comment by GH-James** [comment]
I have tested the workflow

make env
. env/bin/activate
make py
cd into a model
tbuild all <model>

As long as python3.10 is available on your machine the errors should be fixed

Notably, typed-ast was removed as a requirement as ast is now a standard part of python

Coconut requirement version was bumped, which resulted in deprecated syntax 
These were subsequently corrected

**Comment by andrewbutterfield** [comment]
It works perfectly - thanks !

**Pull request merged**
