### PR TITLE
Automatically generate tc-<model>.c

### LINKED ISSUE #18: automate tc-<model>.c generation
We want to automatically generate the tc- files which currently have to be hand edited whenever a revised PML model changes number of tests.

e.g. `formal/promela/models/events/tc-event-mgr-model.c`

### PR DESCRIPTION
**Pull request by GH-James**
Closes #18

### CODE REVIEW

**Comment by GH-James** [comment]
Generated files mostly match those that existed previously

Notably, tc-event-mgr-model.c is different
It now has 2 more test cases as mentioned in a comment on #18 
It is also now structured differently, as some of the preamble was previously between test case function calls

**Review by andrewbutterfield — CHANGES_REQUESTED** [review]
You need to change this back, or at least just remove any excess files.

In general all the different testsuites should be accumulated. The facility to zero the testsuites is useful when you want to focus on one model, but normally all the models should be present. (See new comment on #17)

**Comment by andrewbutterfield** [comment]
> (Commit 0b2b942 )You need to change this back, or at least just remove any excess files.
> 
> In general all the different testsuites should be accumulated. The facility to zero the testsuites is useful when you want to focus on one model, but normally all the models should be present. (See new comment on #17)
> 
> The tc-....-post.h file in `messages` is missing the closing bracket.

You missed this ! See my previous comment above

**Review by andrewbutterfield — APPROVED** [review]

**Comment by andrewbutterfield** [comment]
Now done -  make sure you get any changes I made to main before doing the next task (there may be none!)

**Pull request merged**
