### PR TITLE
Make testbuilder.py language agnostic

### LINKED ISSUE #11: make testbuilder program language agnostic
Have language dependencies defined in a YAML file

### PR DESCRIPTION
**Pull request by GH-James**
- Added refine-config.yml to specify preamble, postamble, rfn, run and test file extension
- Updated spin2test.coco, src/spin2test.coco, src/refine_command.coco to accept these files as input
- Merged changes from master branch

Closes #11

### CODE REVIEW

**Comment by GH-James** [comment]
Tested with all models. All worked without issue except threadq.
Threadq model appears not to compile when running waf command.
This also seems to be the case on the main branch.

These changes will require you to run src.sh again, as the coco files must be recompiled from source.

**Comment by andrewbutterfield** [comment]
The `threadq` model is not ready to go - it's still a work in progress.

This looks good, but I don't want to merge into master just yet - I am in the process of getting a first draft of this stuff into RTEMS.  One possibility is that I create a special deployment branch for that purpose.

I guess we should have a meeting to plan next steps.

**Comment by GH-James** [comment]
I have created a deployment branch, and updated the target branch.

A meeting for next steps makes sense. My next priority is a progress report draft. I will aim to have that done early next week.

**Comment by GH-James** [comment]
One issue I noticed.
If I upgrade the pattern matching and use python 3.10, that will remove the coconut files.
If that is on a separate branch there may be a merge conflict with deleted/kept files.

I think it makes more sense to keep pattern matching related changes on this branch because of that.
I can keep changes local until this is validated and merged.

**Review by andrewbutterfield — COMMENTED** [review]
I am going to have to run this to check it out
(this is in reponse to viewing the commits, not to the comment just above!)

**Comment by andrewbutterfield** [comment]
> One issue I noticed. If I upgrade the pattern matching and use python 3.10, that will remove the coconut files. If that is on a separate branch there may be a merge conflict with deleted/kept files.
> 
> I think it makes more sense to keep pattern matching related changes on this branch because of that. I can keep changes local until this is validated and merged.

I'm unclear about this. What conflicts do you anticipate? I would expect some, but that most would involve disjoint parts of files and so be easy to sort out.

**Comment by GH-James** [comment]
> > One issue I noticed. If I upgrade the pattern matching and use python 3.10, that will remove the coconut files. If that is on a separate branch there may be a merge conflict with deleted/kept files.
> > I think it makes more sense to keep pattern matching related changes on this branch because of that. I can keep changes local until this is validated and merged.
> 
> I'm unclear about this. What conflicts do you anticipate? I would expect some, but that most would involve disjoint parts of files and so be easy to sort out.

My concern comes from the fact that the coconut files will be deleted, and the subsequent changes will be made to python files.

The current changes will not be tracked as the coconut file will be removed.

**Review by andrewbutterfield — APPROVED** [review]
OK - it runs fine for me - accepted

**Pull request merged**
